app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://bueno-ws.ch,https://www.bueno-ws.ch}
app.jwt.issuer=${APP_JWT_ISSUER:https://bueno-ws.ch}
app.public-base-url=${APP_PUBLIC_BASE_URL:https://api.bueno-ws.ch}
app.security.require-https=${APP_SECURITY_REQUIRE_HTTPS:true}

server.forward-headers-strategy=${SERVER_FORWARD_HEADERS_STRATEGY:framework}

spring.session.jdbc.initialize-schema=${SPRING_SESSION_JDBC_INITIALIZE_SCHEMA:never}
spring.docker.compose.enabled=false

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

spring.config.import=aws-secretsmanager:PostgresProdCredentials
spring.cloud.aws.region.static=eu-central-2
spring.datasource.username=${username}
spring.datasource.password=${password}