spring.application.name=buenws-backend

spring.datasource.url=jdbc:postgresql://localhost:2987/buenows-main
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=5Ak94NiJqIBfY76By2i5

admin.email=admin@buenows.com
admin.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.docker.compose.enabled=false
spring.session.jdbc.initialize-schema=always

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=info.buenows@gmail.com
spring.mail.password=${email.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.config.import=optional:classpath:secrets.properties