app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://bueno-ws.ch,https://www.bueno-ws.ch}
app.jwt.issuer=${APP_JWT_ISSUER:https://bueno-ws.ch}
app.public-base-url=${APP_PUBLIC_BASE_URL:https://api.bueno-ws.ch}

server.forward-headers-strategy=${SERVER_FORWARD_HEADERS_STRATEGY:framework}

spring.docker.compose.enabled=false

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}


spring.config.import=aws-secretsmanager:postgres-buenows-secret,aws-secretsmanager:buenows-tokens

spring.cloud.aws.secretsmanager.enabled=true
spring.cloud.aws.region.static=eu-central-2

spring.datasource.url=jdbc:postgresql://${host}:${port:5432}/${dbname:postgres}
spring.datasource.username=${username}
spring.datasource.password=${password}


JWT_SECRET=${JWT_SECRET}
HASH_SALT=${HASH_SALT}
EMAIL_PWD=${EMAIL_PWD}

spring.session.jdbc.initialize-schema=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=info.buenows@gmail.com
spring.mail.password=${EMAIL_PWD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
