CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users
(
    user_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email      VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(50),
    last_name  VARCHAR(50),
    password   VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_authorities
(
    user_id   UUID        NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_user_authorities_users FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS inquiries
(
    inquiry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255),
    title      VARCHAR(255),
    message    TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refresh_tokens
(
    token_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID NOT NULL UNIQUE,
    token      TEXT,
    created_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    CONSTRAINT fk_refresh_tokens_users FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_assets
(
    asset_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID        NOT NULL,
    type       VARCHAR(20) NOT NULL,
    url        TEXT        NOT NULL,
    path       TEXT        NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_assets_users FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS otp_auth
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    otp_code       VARCHAR(255),
    attempts       INTEGER NOT NULL DEFAULT 0,
    active         BOOLEAN NOT NULL DEFAULT FALSE,
    verified_token UUID UNIQUE,
    contact        VARCHAR(255) UNIQUE,
    updated_at     TIMESTAMPTZ,
    expires_at     TIMESTAMPTZ,
    cooldown       TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_user_authorities_user_id ON user_authorities (user_id);
CREATE INDEX IF NOT EXISTS idx_user_assets_user_id ON user_assets (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens (user_id);
