CREATE TABLE IF NOT EXISTS chatbot_conversations
(
    conversation_id UUID PRIMARY KEY,
    session_id      UUID UNIQUE NOT NULL,
    company_key     VARCHAR(120) NOT NULL,
    company_name    VARCHAR(255) NOT NULL,
    language        VARCHAR(8) NOT NULL,
    status          VARCHAR(40) NOT NULL,
    message_count   INTEGER NOT NULL DEFAULT 0,
    preview         TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at        TIMESTAMPTZ,
    expires_at      TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS chatbot_messages
(
    message_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id UUID NOT NULL,
    sequence_number INTEGER NOT NULL,
    role            VARCHAR(24) NOT NULL,
    content         TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chatbot_messages_conversations
        FOREIGN KEY (conversation_id) REFERENCES chatbot_conversations (conversation_id) ON DELETE CASCADE,
    CONSTRAINT uk_chatbot_messages_conversation_sequence UNIQUE (conversation_id, sequence_number)
);

CREATE INDEX IF NOT EXISTS idx_chatbot_conversations_company_created
    ON chatbot_conversations (company_key, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_chatbot_conversations_expires
    ON chatbot_conversations (expires_at);

CREATE INDEX IF NOT EXISTS idx_chatbot_messages_conversation_sequence
    ON chatbot_messages (conversation_id, sequence_number);
