DROP TABLE IF EXISTS orders CASCADE ;
DROP TABLE IF EXISTS customers CASCADE ;
DROP TABLE IF EXISTS products CASCADE ;
DROP TABLE IF EXISTS order_items CASCADE ;
DROP TABLE IF EXISTS user_authorities CASCADE ;
DROP TABLE IF EXISTS refresh_tokens CASCADE ;
DROP TABLE IF EXISTS inquiries CASCADE ;
DROP TABLE IF EXISTS user_assets CASCADE ;
DROP TABLE IF EXISTS otp_auth CASCADE ;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users
(
    user_id    uuid PRIMARY KEY NOT NULL,
    email      VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(50)         NOT NULL,
    last_name  VARCHAR(50)         NOT NULL,
    password   VARCHAR(255)        NOT NULL,
    created_at TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_authorities
(
    user_id   uuid        NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_user_authorities_users FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE inquiries
(
    inquiry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL,
    title      VARCHAR(255),
    message    TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refresh_tokens
(
    token_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    uuid        NOT NULL,
    token      TEXT        NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_refresh_tokens_users FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE otp_auth
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    otp_code       VARCHAR(100)     DEFAULT NULL,
    attempts       INTEGER NOT NULL DEFAULT 4,
    active         BOOLEAN NULL     DEFAULT FALSE,
    verified_token uuid             DEFAULT NULL UNIQUE,
    contact        VARCHAR(100) UNIQUE,
    updated_at     TIMESTAMPTZ      DEFAULT Null,
    expires_at     TIMESTAMPTZ      DEFAULT NULL,
    cooldown       TIMESTAMPTZ
);

create table products (
                          id bigint generated always as identity primary key,
                          name varchar(255) not null,
                          description text,
                          price numeric(12, 2) not null,
                          stock_quantity integer not null default 0,
                          created_at timestamptz not null default now()
);

create table orders (
                        id bigint generated always as identity primary key,
                        customer_id uuid not null references users(user_id),
                        status varchar(50) not null default 'pending',
                        total numeric(12, 2) not null,
                        created_at timestamptz not null default now()
);

create table order_items (
                             id bigint generated always as identity primary key,
                             order_id bigint not null references orders(id),
                             product_id bigint not null references products(id),
                             quantity integer not null,
                             price numeric(12, 2) not null
);

