DROP TABLE IF EXISTS user_authorities;I9#441Bcg&8*cI#%ARs
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS inquiries;
DROP TABLE IF EXISTS user_assets;
DROP TABLE IF EXISTS otp_auth;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users
(
    user_id    uuid PRIMARY KEY DEFAULT NOT NULL,
    email      VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(50)         NOT NULL,
    last_name  VARCHAR(50)         NOT NULL,
    password   VARCHAR(255)        NOT NULL,
    created_at TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_authorities
(
    user_id   uuid        NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_user_authorities_users FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE inquiries
(
    inquiry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL,
    title      VARCHAR(255),
    message    TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refresh_tokens
(
    token_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    uuid        NOT NULL,
    token      TEXT        NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_refresh_tokens_users FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE user_assets
(
    asset_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    uuid        NOT NULL,
    type       VARCHAR(20) NOT NULL,
    url        TEXT        NOT NULL,
    path       TEXT        NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_assets_users FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE otp_auth
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    otp_code       VARCHAR(100)     DEFAULT NULL,
    attempts       INTEGER NOT NULL DEFAULT 4,
    active         BOOLEAN NULL     DEFAULT FALSE,
    verified_token uuid             DEFAULT NULL UNIQUE,
    contact        VARCHAR(100) UNIQUE,
    updated_at     TIMESTAMPTZ      DEFAULT Null,
    expires_at     TIMESTAMPTZ      DEFAULT NULL,
    cooldown       TIMESTAMPTZ
);
CREATE INDEX idx_user_authorities_user_id ON user_authorities(user_id);
CREATE INDEX idx_user_assets_user_id ON user_assets(user_id);