DROP TABLE IF EXISTS user_authorities;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS inquiries;

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(255),
    username VARCHAR(255)
);

CREATE TABLE user_authorities (
                                  user_id BIGINT NOT NULL,
                                  authority VARCHAR(255),
                                  CONSTRAINT fk_user_authorities_users
                                      FOREIGN KEY (user_id)
                                          REFERENCES users (user_id)
                                          ON DELETE CASCADE
);

CREATE TABLE inquiries(
                          email VARCHAR(255),
                          title VARCHAR(255),
                          message TEXT,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_authorities_user_id ON user_authorities(user_id);